website/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="home"),
    path('about', views.about, name="about"),
    path('test', views.test, name="test"),
]

website/management/urls.py
from django.urls import path
from . import views

app_name = 'management'

urlpatterns = [
    path('', views.main_management, name="main_management"),
    path('tasks/create/', views.create_task, name='create_task'),
    path('save_task/', views.save_task, name='save_task'),
    path('delete_task/<int:task_id>/', views.delete_task, name='delete_task'),
    path('get_task_details/<int:task_id>/', views.get_task_details, name='get_task_details'),
    path('update_subtask/', views.update_subtask, name='update_subtask'),
]

website/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.news_home, name="news_home"),
    path('create', views.create, name="create"),
    path('<int:pk>', views.NewsDetailView.as_view(), name="news-detail"),
    path('<int:pk>/update', views.NewsUpdateView.as_view(), name="news-update"),
    path('<int:pk>/delete', views.NewsDeleteView.as_view(), name="news-delete"),
]

website/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('registration/', views.registration, name="registration"),
    path('profile/', views.profile, name="profile"),
    path('logout/', views.logout, name="logout"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('user/', include('users.urls', namespace='user')),
    path('management/', include('management.urls', namespace='management')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/main/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic import DetailView


def index(request):
    data = {
        'title': 'Главная страница ᕦ(ò_óˇ)ᕤ ',
        'values': ['Some', 'Tyt', 'Kak']
    }
    return render(request, 'main/index.html', data)


def about(request):
    return render(request, 'main/about.html')


def test(request):
    return render(request, 'users/test.html')

website/main/templates/main/about.html
{% extends 'main/layout.html' %}

{% block title  %}Страница о себе{% endblock %}


{% block content  %}
    <div class="features">
        <h1>О нас</h1>
        <p>Крутая компания</p>
<!--        <button class="btn btn-danger">Нажми</button>-->
    </div>

{% endblock %}

website/main/templates/main/index.html
{% extends 'main/layout.html' %}

{% block title  %} {{ title }} {% endblock %}


{% block content  %}
    <div class="features">
        <h1>{{ title }}</h1>
        <p>Добро пожаловать на главную страницу! Здесь вы найдете основную информацию.</p>
        <button class="btn btn-warning">Про нас</button>
        {% comment %}
        {% for el in values %}
            {% if el == 'Kak' %}
                <p>{{ el }}</p>
            {% endif %}
        {% endfor %}
        {% endcomment %}
    </div>
{% endblock %}

website/main/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>


    <aside>
        <h3>Навигация</h3>
        <ul>
            <a href="{% url 'main:home' %}"><li><i class="bi bi-house-door"></i> Главная</li></a>
            <a href="{% url 'main:about' %}"><li><i class="bi bi-person-fill"></i> Про нас</li></a>
            {% if user.is_admin or user.is_staff %}
                <a href="{% url 'news:news_home' %}"><li><i class="bi bi-newspaper"></i> Новости</li></a>
                <a href="#"><li><i class="bi bi-telegram"></i> Контакты</li></a>
                <a href="{% url 'news:create' %}"><li><button class="btn btn-info"><i class="bi bi-plus-circle-fill"></i> Создать запись </button></li></a>
            {% endif %}
            <a href="{% url 'management:main_management' %}"><li><i class="bi bi-briefcase"></i> Проект</li></a>
        </ul>
    </aside>
    <div id="resizer" style="display: none;"></div> <!-- Скрываем элемент resizer -->
    <header class="header">
        <div class="header-content">
<!--            <a href="#" class="logo">Логотип</a>-->
            {% if user.is_authenticated %}
                {% if request.path == '/management/' %}
                <div class="other">
                    <nav>
                        <a href="#">Диаграмма Ганта</a>
                        <a href="#">Календарь</a>
                        <a href="#">Ресурсы</a>
                    </nav>
                </div>
                {% endif %}
                {% if not request.path == '/management/' %}
                    <div class="other">
                        <nav>
                            <a href="#"> </a>
                            <a href="#"> </a>
                            <a href="#"> </a>
                        </nav>
                    </div>
                {% endif %}
            {% endif %}

            {% if not user.is_authenticated %}
            <div class="other">
                    <nav>
                        <a href="#"> </a>
                        <a href="#"> </a>
                        <a href="#"> </a>
                    </nav>
                </div>
            {% endif %}
            <div class="auth-links">
                {% if not user.is_authenticated %}
                    <a href="{% url 'user:registration' %}"><li><i class="bi bi-person-add"></i> Регистрация</li></a>
                    <a href="{% url 'user:login' %}"><li><i class="bi bi-person"></i> Войти</li></a>
                {% else %}
                    {% if user.is_admin or user.is_staff %}
                        <a href="{% url 'admin:index' %}"><li><i class="bi bi-pc-display"></i> Админка</li></a>
                    {% endif %}
                    <a href="{% url 'user:logout' %}"><li><i class="bi bi-box-arrow-left"></i> Выйти</li></a>
                    <a href="{% url 'user:profile' %}"><li><i class="bi bi-person-circle"></i> Профиль</li></a>
                {% endif %}
            </div>
        </div>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>


    <script>
        // Добавляем класс 'loaded' к body после полной загрузки страницы
        window.addEventListener('load', function() {
            document.body.classList.add('loaded');
        });
    </script>
    <script src="{% static 'main/js/resize.js' %}"></script>
    <script src="{% static 'main/js/task.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</body>
</html>

website/main/templates/main/profile.html
{% extends 'main/layout.html' %}

{% block title  %}Profile{% endblock %}


{% block content  %}


{% endblock %}

website/main/templates/main/test.html
{% extends 'main/layout.html' %}

{% block title %} TEST {% endblock %}


{% block content %}
<div class="features">

<p>ABOBAA 111Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor eaque excepturi
    facere fugit id illo illum iusto labore laboriosam magnam nisi non odit perspiciatis
    porro quisquam repellat repudiandae soluta, sunt?
</p>
</div>
{% endblock %}