website/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="home"),
    path('about', views.about, name="about"),
    path('test', views.test, name="test"),
]

website/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('registration/', views.registration, name="registration"),
    path('profile/', views.profile, name="profile"),
    path('logout/', views.logout, name="logout"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('user/', include('users.urls', namespace='user')),
    path('management/', include('management.urls', namespace='management')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    image = models.ImageField(upload_to='users_image', blank=True, null=True, verbose_name='Аватар')

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

website/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from .models import User


class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()


    # username = forms.CharField(
    #     widget=forms.TextInput(attrs={"autofocus": True,
    #                                   'class': 'form-control',
    #                                   'placeholder': 'Логин'})
    # )
    # password = forms.CharField(
    #     widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
    #                                       'class': 'form-control',
    #                                       'placeholder': 'Пароль'}
    #                                ),
    # )

class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        ]

        first_name = forms.CharField()
        last_name = forms.CharField()
        username = forms.CharField()
        email = forms.CharField()
        password1 = forms.CharField()
        password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'image',
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        ]

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    # password = forms.CharField()

website/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import UserLoginForm, UserRegistrationForm, ProfileForm


# Create your views here.


def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                # messages.success(request, f"{username}, с возвращением!")

                if request.POST.get('next', None):
                    return HttpResponseRedirect(reverse.POST.get('next'))

                return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Home - Авторизация',
        'form': form,
    }
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            # messages.success(request, f"{user.username}, добро пожаловать!")
            return HttpResponseRedirect(reverse('main:home'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Registration - Регистрация',
        'form': form,
    }
    return render(request, 'users/registration.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            # messages.success(request, f"Так-то лучше. Профиль обновлён!")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)

    context = {
        'title': 'Profile - Профиль',
        'form': form,
    }
    return render(request, 'users/profile.html', context)


@login_required
def logout(request):  # <li><a class="dropdown-item  text-white" href="{% url "user:logout" %}">Выйти</a></li>
    # messages.success(request, f"{request.user.username}, Вы вышли из под аккаунта!")
    auth.logout(request)
    return redirect(reverse('main:home'))

website/users/templates/users/login.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %} Вход {% endblock %}

{% block content %}
    <div class="login-container">
        <h1>Войти</h1>
        <form method="post" action="{% url 'user:login' %}">
            {% csrf_token %}
<!--            <span>{{ error }}</span><br>  -->
                {% if request.GET.next %}
                <input type="hidden" name="text" value="{{ request.GET.next }}">
            {% endif %}

            <input type="text" placeholder="Логин" name="username" id="id_username" class="form-control" autofocus
                   value="{{ forms.username.value }}"
                   required> <br>

            {% if form.username.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
            {% endif %}

            <input type="password" placeholder="Пароль" name="password" id="id_password" class="form-control" required> <br>

            {% if form.password.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.password.errors}}</div>
            {% endif %}

            {% comment %}
            {% for item in form %}
                {{ item }}
            {% endfor %}
            {% endcomment %}


            {% comment %} {{ form.username }} {% endcomment %}

            {% comment %} {{ form.password }} {% endcomment %}
            <button class="btn btn-success" type="submit">Войти</button>
        </form>
    </div>
{% endblock %}

website/users/templates/users/profile.html
<!-- profile.html -->
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}Профиль{% endblock %}

{% block content %}
<div class="profile-container">
    <div class="profile-header">
        <h1>Профиль</h1>
    </div>
    <div class="profile-info">
        {% if user.image %}
                <img src="{{ user.image.url }}" alt="User Photo" class="profile-photo">
            {% else %}
                <img src="{% static 'users/img/profile.png' %}" alt="User Photo" style="max-width: 150px;" class="profile-photo">
             {% endif %}
        <h2>{{ form.username.value }}</h2>
        <p>{{ form.last_name.value }}</p>
        <p>{{ form.email.value }}</p>
    </div>

    <div class="profile-edit">
        <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}




            <input type="file" class="form-control" placeholder="Загрузить фото" id="id_image" name="image" accept="image/*">
            {% if form.image.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
            {% endif %}

            <label for="id_username" class="form-label">Имя пользователя</label>
            <input type="text" class="form-control" placeholder="Имя пользователя"
                   id="id_username"
                   name="username"
                   value="{{ form.username.value }}">
            {% if form.username.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
            {% endif %}

            <label for="id_first_name" class="form-label">Имя</label>
            <input type="text" class="form-control" placeholder="Имя"
                   id="id_first_name"
                   name="first_name"
                   value="{{ form.first_name.value }}">
            {% if form.first_name.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
            {% endif %}

            <label for="id_last_name" class="form-label">Фамилия</label>
            <input type="text" class="form-control" placeholder="Фамилия"
                   id="id_last_name"
                   name="last_name"
                   value="{{ form.last_name.value }}">
            {% if form.last_name.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
            {% endif %}

            <label for="id_email" class="form-label">Email</label>
            <input type="email" class="form-control" placeholder="Email"
                   id="id_email"
                   name="email"
                   value="{{ form.email.value }}"
            >
            {% if form.email.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
            {% endif %}

<!--            <input type="password" class="form-control" placeholder="Пароль"-->
<!--                   id="id-password"-->
<!--                   name="password"-->
<!--                   value="{{ form.password.value|length }}"-->
<!--            > <br>-->
<!--            {% if form.password1.errors %}-->
<!--                <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>-->
<!--            {% endif %}-->

            <button class="btn btn-success" type="submit">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

website/users/templates/users/registration.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %} Регистрация {% endblock %}

{% block content %}
    <div class="registration-container">
        <h1>Регистрация</h1>
        <form action="{% url 'user:registration' %}" method="POST">
            {% csrf_token %}
            <span>{{ error }}</span><br>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <input type="text" placeholder="Введите ваше имя"
                           value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                           class="form-control" name="first_name" id="id_first_name" required>
                    {% if form.first_name.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                    {% endif %}
                </div>
                <div class="form-group col-md-6">
                    <input type="text" placeholder="Введите вашу фамилию"
                           value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                           class="form-control" name="last_name" id="id_last_name" required>
                    {% if form.last_name.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                    {% endif %}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <input type="text" placeholder="Введите ваше имя пользователя"
                           value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                           class="form-control" name="username" id="id_username" required>
                    {% if form.username.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                    {% endif %}
                </div>
                <div class="form-group col-md-6">
                    <input type="email" placeholder="Введите ваш email"
                           value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                           class="form-control" name="email" id="email" required>
                    {% if form.email.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                    {% endif %}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <input type="password" placeholder="Введите ваш пароль"
                           value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                           class="form-control" name="password1" id="id_password1" required>
                    {% if form.password1.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                    {% endif %}
                </div>
                <div class="form-group col-md-6">
                    <input type="password" placeholder="Подтвердите ваш пароля"
                           value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                           class="form-control" name="password2" id="id_password2" required>
                    {% if form.password2.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                    {% endif %}
                </div>
            </div>
            <button class="btn btn-success" type="submit">Зарегистрироваться</button>
        </form>
    </div>
{% endblock %}